teams:
    miway:
        - pierredup
        - royalmitten
        - dhdutoit
        - HendrikGrobler
        - mosekwa
        - smithandre
        - ViGouRCanberra
        - CarmeloNaciti
        - 9tails1
        - RonIce
        - Malise-Obert
        - Zwelibanzi
        - DanJohn008
        - omphemetse
    afrihost:
        - sarelvdwalt
        - mostertb
        - Owkkuri
        - sacheen
        - johnathanmdell
        - awesome-fortune
        - luketruter
        - leepelser
        - Dorfling
        - Syb3r1us
        - prashant8821
        - Sunjalo
        - sanushen
        - derde
invalid_prs:
    - url: https://github.com/symfony/symfony/pull/24511
      reason: Creator closed the PR as invalid
    - url: https://github.com/mostertb/fizzbuzz/pull/1
      reason: PR was created to team members project
    - url: https://github.com/dhdutoit/octocom/pull/3
      reason: PR was created to team members project
